# Generated by Django 4.0.3 on 2022-08-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('bloodbankid', models.IntegerField(primary_key=True, serialize=False)),
                ('bbname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contactPerson', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=500)),
                ('usertype', models.CharField(default='Guest', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiverid', models.IntegerField(primary_key=True, serialize=False)),
                ('rcname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=4)),
                ('qty_req', models.IntegerField()),
                ('alloted_bloodbagno', models.IntegerField()),
                ('request_no', models.IntegerField()),
                ('request_dt', models.DateField()),
                ('request_status', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('bloodbankid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bloodbank')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donorid', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=4)),
                ('qty', models.CharField(max_length=6)),
                ('bloodbagno', models.IntegerField()),
                ('bloodCollectiondt', models.DateField()),
                ('bloodExpirydt', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('bloodbankid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bloodbank')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_no', models.IntegerField()),
                ('comp_name', models.CharField(max_length=20)),
                ('comp_phone', models.CharField(max_length=10)),
                ('comp_msg', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser'),
        ),
    ]
